si j'avais un marteau

diff --git a/raspberry/vertx b/raspberry/vertx
--- a/raspberry/vertx
+++ b/raspberry/vertx
@@ -5,28 +5,74 @@
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Starts vertx as service
-# Description:       This file should be used to construct scripts to be
-#                    placed in /etc/init.d.
+# Short-Description: Vert.x starter for specific module kouign-amann
+# Description:       Vert.x starter for specific module kouign-amann
 ### END INIT INFO
 
-# Author: Foo Bar <foobar@baz.org>
+# Author: Aurélien Maury <amaury@xebia.fr>
 #
-# Please remove the "Author" lines above and replace them
-# with your own name if you copy and modify this script.
-
 # Do NOT "set -e"
 
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:bin/javac::")
-export VERTX_HOME=/opt/vertx
-export VERTX_MODS=$VERTX_HOME/mods
-EXTRA_ARGS="--chuid vertx:vertx"
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:$VERTX_HOME/bin:$JAVA_HOME/bin
-DESC="Description of the service"
-NAME=Vert.x
-DAEMON=$VERTX_HOME/bin/vertx
-DAEMON_ARGS="runzip $VERTX_HOME/deploy/pi-0.1.zip -conf $VERTX_HOME/conf/kouign-amann.conf"
+##############
+
+MODULE=fr.xebia.kouignamann~pi~0.1
+MODULE_CONF=$VERTX_MODS_CONF/kouign-amann.conf
+
+# Add default JVM options here. You can also use JAVA_OPTS and VERTX_OPTS to pass JVM options to this script.
+
+VERTX_OPTS=""
+# VERTX_OPTS="-Dvertx.serialiseBlockingActions=true"
+
+JVM_OPTS=""
+# If you're deploying and undeploying a lot of verticles with dynamic languages it's recommended to enable GC'ing
+# of generated classes and prevent OOM due to a lot of gc
+# JVM_OPTS="-XX:+CMSClassUnloadingEnabled -XX:-UseGCOverheadLimit"
+
+JMX_OPTS=""
+# To enable JMX uncomment the following
+# JMX_OPTS="-Dcom.sun.management.jmxremote -Dvertx.management.jmx=true -Dhazelcast.jmx=true"
+
+# Use the maximum available, or set MAX_FD != -1 to use that value.
+MAX_FD="maximum"
+
+# Attempt to set VERTX_HOME
+export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
+export VERTX_HOME=/home/pi/vertx_home
+export VERTX_MODS=/home/pi/vertx_mods
+export VERTX_MODS_CONF=/home/pi/vertx_mods_conf
+export LANG=en_GB.UTF-8
+
+CLASSPATH=${CLASSPATH}:${VERTX_HOME}/conf:${VERTX_HOME}/lib/*:$VERTX_MODS
+
+# Increase the maximum file descriptors if we can.
+MAX_FD_LIMIT=`ulimit -H -n`
+if [ $? -eq 0 ] ; then
+    if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
+        MAX_FD="$MAX_FD_LIMIT"
+    fi
+    ulimit -n $MAX_FD
+    if [ $? -ne 0 ] ; then
+        warn "Could not set maximum file descriptor limit: $MAX_FD"
+    fi
+else
+    warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
+fi
+
+if [ "x" != "x$VERTX_MODS" ]; then
+  VERTX_OPTS="$VERTX_OPTS -Dvertx.mods=$VERTX_MODS"
+fi
+
+##############
+
+DESC="Vert.x instance of kouign-amann-pi module"
+NAME=vertx
+DAEMON=$JAVA_HOME/bin/java
+DAEMON_ARGS="$JVM_OPTS $JAVA_OPTS $JMX_OPTS $VERTX_OPTS
+    -Djava.util.logging.config.file=${VERTX_JUL_CONFIG:-${VERTX_HOME}/conf/logging.properties}
+    -Dvertx.home=$VERTX_HOME
+    -Dvertx.clusterManagerFactory=org.vertx.java.spi.cluster.impl.hazelcast.HazelcastClusterManagerFactory
+    -classpath $CLASSPATH
+    org.vertx.java.platform.impl.cli.Starter runmod $MODULE -conf $MODULE_CONF"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
@@ -47,32 +93,31 @@ SCRIPTNAME=/etc/init.d/$NAME
 #
 # Function that starts the daemon/service
 #
+# Return
+#   0 if daemon has been started
+#   1 if daemon was already running
+#   2 if daemon could not be started
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon $EXTRA_ARGS --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon $EXTRA_ARGS --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+    date > /tmp/beforevertx
+    START_STOP_DAEMON_OPTS="--start --quiet --background --chuid $USER --pidfile $PIDFILE --exec $DAEMON"
+
+    start-stop-daemon $START_STOP_DAEMON_OPTS --test > /dev/null \
+	|| return 1
+    start-stop-daemon $START_STOP_DAEMON_OPTS --make-pidfile -- $DAEMON_ARGS \
+	|| return 2
 }
 
 #
 # Function that stops the daemon/service
 #
+# Return
+#   0 if daemon has been stopped
+#   1 if daemon was already stopped
+#   2 if daemon could not be stopped
+#   other if a failure occurred
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
 	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
@@ -154,10 +199,8 @@ case "$1" in
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
 	exit 3
 	;;
 esac
-
 :
